---
- become: true
  hosts: test
  name: "installing_git_&_maven"
  tasks:
    - apt:
        name: git
        update_cache: true
      name: "node_updated_for_git"
    - apt:
        name: git
        state: latest
      name: "git_installed_successfully"
    - apt:
        name: maven
        update_cache: true
      name: "node_updated_for_maven"
    - apt:
        name: maven
        state: latest
      name: "maven_installed_successfully"
